# Generated by Django 4.2.1 on 2024-05-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_markedcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
    ]
